[tool.poetry]
name = "mypreprocessing"
version = "0.1.0"
description = ""
authors = ["bartl <bartlomiejpieper.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
pandas = "2.2.2"
nltk = "3.8.1"
tensorflow = "2.10"
tensorflow-io-gcs-filesystem = "0.27.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
