[tool.poetry]
name = "myvisualization"
version = "0.1.0"
description = ""
authors = ["bartl <bartlomiejpieper.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
seaborn = "0.13.2"
matplotlib = "3.8.4"
pandas = "2.2.2"
scikit-learn = "1.5.2"
numpy = "1.26.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
